trigger: none

pool: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run
  displayName: 'npm build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '*.tgz' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy npm package'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'package.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy package.json'   

- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: '$(Build.ArtifactStagingDirectory)/npm'
    publishRegistry: 'useFeed'
    publishFeed: '042dd846-7988-4cc9-93a0-8d3131557793/d9964051-6c51-4733-9638-3b8805165e52'
